name: Performance Tests

on:
  workflow_dispatch:

jobs:
  latency-test:
    name: Latency Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'zulu'
      - uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run latency test
        run: mvn -Dtest=PerfLatency#testLatencyMargin test

  serialization-test:
    name: Serialization Test
    runs-on: ubuntu-latest
    needs: latency-test
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'zulu'
      - uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run serialization test
        run: mvn -Dtest=PerfPersistence#testPersistenceMargin test

  throughput-test:
    name: Throughput Test
    runs-on: ubuntu-latest
    needs: serialization-test
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'zulu'
      - uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run throughput test
        run: mvn -Dtest=PerfThroughput#testThroughputMargin test
