name: Throughput Test

on:
  workflow_dispatch:

jobs:
  throughput-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run throughput test
        run: mvn -Dtest=PerfThroughput#testThroughputMargin test
